apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
    app: frontend server
  template:
    metadata:
      name: sample02
      labels: frontend server
    spec:
      template:
      containers:
        - name: sample1
          image: nginx


