apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: redis
    type: messenger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
        type: messenger
    spec:
      containers:
        - name: redis
          image: redis
