apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  type: messenger
spec:
  replicas: 3
  template:
    metadata:
      name: redis
      labels:
        app: redis
        type: messenger
    spec:
      containers:
        - name: redis
          image: redis
  selector:
  matchLabels:
  type: messenger
